// ─── CUSTOMIZE THIS FILE ──────────────────────────────────────────────────────
//
// Define the TypeScript RPC tools that are available inside the sandbox.
// These become the `codemode.*` namespace — the LLM writes code like:
//
//   async () => {
//     const result = await codemode.search({ query: "something" });
//     await codemode.save({ key: "output", value: result });
//     return result;
//   }
//
// Each tool's `execute` function runs in the HOST Worker (not the sandbox),
// so it has full access to env bindings, external APIs, secrets, etc.
// The sandbox only sees the return value — it cannot access host internals.
//
// TOOL FORMAT:
//   - execute receives a single object argument (destructured below)
//   - Use `positionalArgs: true` in the ToolProvider if you prefer positional style
//   - Return value must be JSON-serializable
//
// ─────────────────────────────────────────────────────────────────────────────

export type DomainTools = typeof domainTools;

export const domainTools = {
  // Example: A trivial key-value store.
  // Replace these with calls to your actual services, databases, APIs, etc.

  kvGet: {
    description:
      "Retrieve a stored value by key. Returns null if not found.",
    execute: async ({ key }: { key: string }): Promise<string | null> => {
      // TODO: replace with your real data store
      // e.g. return env.MY_KV.get(key);
      console.log(`[kvGet] key=${key}`);
      return `stub-value-for-${key}`;
    },
  },

  kvSet: {
    description:
      "Store a string value under a key. Overwrites existing values.",
    execute: async ({
      key,
      value,
    }: {
      key: string;
      value: string;
    }): Promise<void> => {
      // TODO: replace with your real data store
      // e.g. await env.MY_KV.put(key, value);
      console.log(`[kvSet] ${key} = ${value}`);
    },
  },

  kvList: {
    description:
      "List all keys in the store, optionally filtered by prefix.",
    execute: async ({
      prefix,
    }: {
      prefix?: string;
    }): Promise<string[]> => {
      // TODO: replace with your real data store
      // e.g. const { keys } = await env.MY_KV.list({ prefix });
      //      return keys.map(k => k.name);
      return [`${prefix ?? ""}example-key-1`, `${prefix ?? ""}example-key-2`];
    },
  },

  kvDelete: {
    description: "Delete a key from the store. No-op if the key does not exist.",
    execute: async ({ key }: { key: string }): Promise<void> => {
      // TODO: replace with your real data store
      console.log(`[kvDelete] key=${key}`);
    },
  },
};

// ─── TypeScript interface shown to the LLM ───────────────────────────────────
// This is auto-generated by @cloudflare/codemode from the tool descriptors.
// You don't need to maintain this manually — it's here for reference.
//
// declare const codemode: {
//   kvGet(args: { key: string }): Promise<string | null>;
//   kvSet(args: { key: string; value: string }): Promise<void>;
//   kvList(args: { prefix?: string }): Promise<string[]>;
//   kvDelete(args: { key: string }): Promise<void>;
// }
